# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to receive feedback from the Firestone feedback form

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
    Function:
        Runtime: nodejs12.x

Resources:
    ProcessFeedbackFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: feedback.default
            Runtime: nodejs16.x
            CodeUri: ./dist/feedback
            Timeout: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-feedback-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE

Outputs:
    ProcessFeedbackApi:
        Description: URL to post feedback form results
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feedback'
        Export:
            Name: ProcessFeedbackApi
